//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaShoreProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiscGenres
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiscGenres()
        {
            this.Discs = new HashSet<Discs>();
        }
    
        public int id { get; set; }
        public string genreName { get; set; }
        public Nullable<int> typeID { get; set; }
    
        public virtual DiscTypes DiscTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Discs> Discs { get; set; }
    }
}
