//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaShoreProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Discs()
        {
            this.OrderItem = new HashSet<OrderItem>();
        }
    
        public int id { get; set; }
        public string discName { get; set; }
        public Nullable<int> discAuthorID { get; set; }
        public Nullable<int> genreID { get; set; }
        public Nullable<int> discQuantityInStock { get; set; }
        public Nullable<System.DateTime> discReleaseDate { get; set; }
        public string discDescription { get; set; }
        public Nullable<int> discPrice { get; set; }
        public string discCoverPath { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual DiscGenres DiscGenres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItem { get; set; }

        public string ReleaseDate
        {
            get
            {
                return discReleaseDate.HasValue
                    ? discReleaseDate.Value.ToString("dd.MM.yyyy")
                    : "Дата не указана";
            }
        }
        public string quantity
        {
            get
            {
                return $"{discQuantityInStock} шт. осталось";
            }
        }
        public string price
        {
            get
            {
                return $"{discPrice} ₽ / шт.";
            }
        }

    }
}
