//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaShoreProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int id { get; set; }
        public Nullable<int> orderID { get; set; }
        public Nullable<int> discID { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> PriceAtTime { get; set; }
    
        public virtual Discs Discs { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
